name: CI Workflow

on:
  push:
    branches:
      - master
      - lab3
    paths:
      - 'app_python/'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Linter
        run: flake8 app.py app_python/

      - name: Run Unit Tests
        run: python -m unittest discover app_python

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t app_python:latest .
          docker tag shelma13/app_python:latest shelma13/app_python:latest
          docker push shelma13/app_python:latest
